
stages:
  data_params:
    batch_size: 2
    num_workers: 0
    valid_size: 0.2
    loaders_params:
      valid:
        batch_size: 2
state_params:
    num_epochs: 3
    main_metric: accuracy01
    minimize_metric: False

  criterion_params:
    criterion: CrossEntropyLoss

  optimizer_params:
    optimizer: Adam

  callbacks_params:
    accuracy:
      callback: AccuracyCallback
      accuracy_args: [1, 3]
